export const WORKERS = [
  {
    id: 1,
    name: 'John Doe',
    rating: 4.5,
    skills: ['UX Research', 'Web Development'],
    age: 25,
  },
  {
    id: 2,
    name: 'Emily Smith',
    rating: 3.8,
    skills: ['Graphic Design', 'Content Writing'],
    age: 28,
  },
  {
    id: 3,
    name: 'David Johnson',
    rating: 4.2,
    skills: ['Data Analysis', 'Machine Learning'],
    age: 31,
  },
  {
    id: 4,
    name: 'Sophia Anderson',
    rating: 4.7,
    skills: ['Project Management', 'Business Development'],
    age: 29,
  },
  {
    id: 5,
    name: 'Michael Brown',
    rating: 3.9,
    skills: ['Software Engineering', 'Database Management'],
    age: 27,
  },
  {
    id: 6,
    name: 'Olivia Wilson',
    rating: 4.1,
    skills: ['Social Media Marketing', 'Copywriting'],
    age: 26,
  },
  {
    id: 7,
    name: 'Daniel Taylor',
    rating: 4.3,
    skills: ['UI Design', 'Front-end Development'],
    age: 30,
  },
  {
    id: 8,
    name: 'Ava Martinez',
    rating: 4.6,
    skills: ['Content Strategy', 'SEO Optimization'],
    age: 29,
  },
  {
    id: 9,
    name: 'James Thompson',
    rating: 4.0,
    skills: ['Data Visualization', 'Statistical Analysis'],
    age: 32,
  },
  {
    id: 10,
    name: 'Isabella Davis',
    rating: 4.4,
    skills: ['Product Management', 'Agile Methodologies'],
    age: 27,
  },
];
